name: Docker Image CI

on:
  push:
    branches: [master, actions]
  pull_request:
    branches: [master, actions]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Get tag
      #   id: tag
      #   uses: dawidd6/action-get-tag@v1
      # - name: Use tag
      #   run: echo ${{ steps.tag.outputs.tag }}
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump GitHub context
        env:
          DOCKER_IS_TAG: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo [[ $DOCKER_IS_TAG ]] && echo 'tag' || echo 'branch'

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GHCR_TOKEN }}
      # - name: Build and push
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     tags: |
      #       cyrale/linuxgsm:actions
      #       ghcr.io/cyrale/linuxgsm:actions
      # - name: Image digest
      #   run: echo ${{ steps.docker_build.outputs.digest }}
