name: Docker Image CI

on:
  push:
    branches: [master, actions]
  pull_request:
    branches: [master, actions]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push to DockerHub
        id: docker_build_dockerhub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: cyrale/linuxgsm:actions
      - name: Image digest
        run: echo ${{ steps.docker_build_dockerhub.outputs.digest }}
      - name: Login to GitHub Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push to GitHub Registry
        id: docker_build_github
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/cyrale/linuxgsm:actions
      - name: Image digest
        run: echo ${{ steps.docker_build_github.outputs.digest }}
