name: Docker Image CI

on:
  push:
    branches:
      - master
      - actions
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  pull_request:
    branches:
      - master
      - actions

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Extract version_tag
        id: version_tag
        env:
          DOCKER_IS_TAG: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: [[ "$DOCKER_IS_TAG" = true ]] && echo "::set-output name=version_tag::${GITHUB_REF/refs\/tags\/v/}" || ( [[ "${GITHUB_REF/refs\/heads\//}" = "master" ]] && echo "::set-output name=version_tag::latest" || echo "::set-output name=version_tag::${GITHUB_REF/refs\/heads\//}" )
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            cyrale/linuxgsm:${{ steps.version_tag.outputs.version_tag }}
            ghcr.io/cyrale/linuxgsm:${{ steps.version_tag.outputs.version_tag }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
